# Generated by Django 2.1 on 2019-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('openid', models.CharField(max_length=50, verbose_name='用户名')),
                ('count', models.CharField(max_length=10, verbose_name='已查询次数')),
                ('type', models.CharField(default=0, max_length=10, verbose_name='类型')),
                ('status', models.CharField(default=0, max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '包月信息',
                'db_table': 'month_info',
            },
        ),
        migrations.CreateModel(
            name='TransactionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('out_trade_no', models.CharField(max_length=32, unique=True, verbose_name='商户订单号')),
                ('openid', models.CharField(max_length=50, verbose_name='用户名')),
                ('amount', models.CharField(max_length=10, verbose_name='金额')),
                ('type', models.CharField(max_length=10, verbose_name='交易类型')),
                ('status', models.CharField(max_length=10, verbose_name='交易状态')),
            ],
            options={
                'verbose_name': '交易信息',
                'db_table': 'transaction_info',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('openid', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('balance', models.CharField(default=0, max_length=10, verbose_name='余额')),
                ('current', models.CharField(default='null', max_length=50, verbose_name='当前查询项目')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'user_info',
            },
        ),
    ]
