# Generated by Django 2.1 on 2019-08-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configinfo',
            name='count',
            field=models.CharField(default=50, max_length=10, verbose_name='包月每日次数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='promoter',
            field=models.CharField(default='null', max_length=50, verbose_name='推广人'),
        ),
    ]
